'use client';

import type { Metadata } from 'next';
import 'react-datepicker/dist/react-datepicker.css';
import 'react-toastify/dist/ReactToastify.css'; // ✅ Toast 스타일 추가
import '@/styles/globals.css';
import { HeaderProvider } from '@/components/layout/Gnb/HeaderContext';
import ClientHeaderLayout from '@/components/layout/ClientHeaderLayout';
import { ToastContainer } from 'react-toastify'; // ✅ Toast 컴포넌트 import

export const metadata: Metadata = {
  title: 'Coworkers',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className="flex min-h-screen w-full flex-col">
        <HeaderProvider>
          <ClientHeaderLayout />
          <main className="flex-grow">{children}</main>
        </HeaderProvider>
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar={false}
          closeOnClick
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
