import type { Metadata } from 'next';
import '@/styles/globals.css';
import 'react-datepicker/dist/react-datepicker.css';
import { HeaderProvider } from '@/components/layout/Gnb/HeaderContext';
import ClientHeaderLayout from '@/components/layout/ClientHeaderLayout';

export const metadata: Metadata = {
  title: 'Coworkers',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className="bg-bg300 min-h-screen text-white">
        <HeaderProvider>
          <ClientHeaderLayout />
          <main>{children}</main>
        </HeaderProvider>
      </body>
    </html>
  );
}
