import type { Metadata } from 'next';
import Script from 'next/script';
import 'react-datepicker/dist/react-datepicker.css';
import '@/styles/globals.css';
import { HeaderProvider } from '@/components/layout/Gnb/HeaderContext';
import ClientHeaderLayout from '@/components/layout/ClientHeaderLayout';
import GlobalToast from '@/components/GlobalToast';
import InitializeAuth from '@/components/InitializeAuth';
import QueryProvider from './QueryProvider';

export const metadata: Metadata = {
  title: 'Coworkers',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/clover.svg',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <head>
        <Script src="https://developers.kakao.com/sdk/js/kakao.js" strategy="beforeInteractive" />
      </head>
      <body className="flex min-h-screen w-full flex-col">
        <QueryProvider>
          <GlobalToast />
          <InitializeAuth />
          <HeaderProvider>
            <ClientHeaderLayout />
            <main className="flex-grow">{children}</main>
          </HeaderProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
